export const CHARACTERS_LOADED = "CHARACTERS_LOADED";
export const COMICS_LOADED = "COMICS_LOADED";
export const COMIC_LOADED = "COMIC_LOADED";
export const CHARACTERS_FILTERED_LOADED = "CHARACTERS_FILTERED_LOADED";